// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pltkfiibqeatzvnhsodc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsdGtmaWlicWVhdHp2bmhzb2RjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4ODk2MDIsImV4cCI6MjA1ODQ2NTYwMn0.s2Sfh3TY9A_RGb9QuI21v0wJxjq_sppM9z0fo7vyLLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);